# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sql_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(to='music_sql_api.Song'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='music_sql_api.Artist'),
        ),
    ]
