# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sql_api', '0002_auto_20170202_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='music_sql_api.Album'),
        ),
    ]
