# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_sql_api', '0003_auto_20170202_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='music_sql_api.Album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='music_sql_api.Song')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='agency',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
