# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sql_api', '0003_auto_20170211_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
