# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_sql_api', '0007_auto_20170211_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_length',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, default=0),
        ),
    ]
